# SageMaker Demo: Employee Attrition Prediction Using Feature Store and XGBoost

This notebook demonstrates how to use Amazon SageMaker's Feature Store and XGBoost built-in algorithm to predict employee attrition.

In [1]:
!pip install pandas cffi sagemaker sagemaker-feature-store-pyspark
!pip install --upgrade sagemaker

import sagemaker
print(dir(sagemaker))

Requirement already satisfied: pandas in /opt/conda/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: cffi in /opt/conda/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: sagemaker in /opt/conda/lib/python3.12/site-packages (3.11.0)
Requirement already satisfied: sagemaker-feature-store-pyspark in /opt/conda/lib/python3.12/site-packages (2.0.0)
Requirement already satisfied: numpy>=1.26.0 in /opt/conda/lib/python3.12/site-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.12/site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas) (2026.2)
Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi) (2.22)
Requirement already satisfied: sagemaker-core<3.0.0,>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (2.11.0)
Requirement already satisfied: sagemaker-train<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: sagemaker-serve<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: sagemaker-mlops<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: boto3<2.0.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.42.91)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.13.4)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.0.3)
Requirement already satisfied: jsonschema<5.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.23.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.9.6)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.10.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.15.0)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.33.1)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (23.2.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (25.0)
Requirement already satisfied: protobuf<7.0.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.33.6)
Requirement already satisfied: smdebug_rulesconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.0.1)
Requirement already satisfied: schema>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.7.7)
Requirement already satisfied: omegaconf>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.3.0)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.16.3)
Requirement already satisfied: cloudpickle>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.2.1)
Requirement already satisfied: paramiko>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.0)
Requirement already satisfied: tblib>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.0.0)
Requirement already satisfied: cryptography>=46.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (46.0.7)
Requirement already satisfied: botocore<1.43.0,>=1.42.91 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.42.91)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.16.1)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.91->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.26.20)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.23.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.7.0)

Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.4.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.20.0)
Requirement already satisfied: pyiceberg>=0.8.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.11.1)
Requirement already satisfied: pyarrow>=14.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (21.0.0)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (2026.3.0)
Requirement already satisfied: deepdiff in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (9.0.0)
Requirement already satisfied: mlflow in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.11.1)
Requirement already satisfied: sagemaker_schema_inference_artifacts in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.0.5)
Requirement already satisfied: pytest in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (9.0.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.67.3)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.9.8)
Requirement already satisfied: tritonclient[http] in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.41.1)
Requirement already satisfied: onnx in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.20.0)
Requirement already satisfied: onnxruntime in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.24.2)
Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.8.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.4.3)
Requirement already satisfied: jinja2<4.0,>=3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.1.6)
Requirement already satisfied: sagemaker-mlflow<1.0.0,>=0.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (0.3.0)
Requirement already satisfied: nest_asyncio>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (1.6.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<4.0,>=3.0->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.0.3)
Requirement already satisfied: Flask-CORS<7 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.0.2)
Requirement already satisfied: Flask<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.3)
Requirement already satisfied: aiohttp<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.18.4)
Requirement already satisfied: cachetools<8,>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (8.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.105.0)

Requirement already satisfied: docker<8,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (7.1.0)
Requirement already satisfied: fastapi<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.48)
Requirement already satisfied: gunicorn<26 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (23.0.0)
Requirement already satisfied: huey<3,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.6.0)
Requirement already satisfied: matplotlib<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.10.9)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.0)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.2.2)
Requirement already satisfied: scikit-learn<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.7.2)
Requirement already satisfied: skops<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.0.49)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.5.0)
Requirement already satisfied: uvicorn<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.22.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.23.0)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.3.12)
Requirement already satisfied: google-auth~=2.0 in /opt/conda/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.49.2)

Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.4.2)

Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b0 in /opt/conda/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.62b0)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in /opt/conda/lib/python3.12/site-packages (from skops<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.17.0)

Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.5.0)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.16.0)
Requirement already satisfied: setuptools<82 in /opt/conda/lib/python3.12/site-packages (from sagemaker-feature-store-pyspark) (81.0.0)

Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.1.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf>=2.1.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.9.3)
Requirement already satisfied: bcrypt>=3.2 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (5.0.0)
Requirement already satisfied: invoke>=2.0 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.0.3)
Requirement already satisfied: pynacl>=1.5 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.6.2)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prettytable>=3.9->skops<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.6.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/conda/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.6.3)

Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (5.2.1)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (2026.3.0)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.0.4)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.25.0)

Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.46.0->fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.13.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.29.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.6.1)
Requirement already satisfied: mpmath<1.5,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.4.1)

Requirement already satisfied: orderly-set<6,>=5.5.0 in /opt/conda/lib/python3.12/site-packages (from deepdiff->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.5.0)
Requirement already satisfied: ml_dtypes>=0.5.0 in /opt/conda/lib/python3.12/site-packages (from onnx->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.5.4)

Requirement already satisfied: flatbuffers in /opt/conda/lib/python3.12/site-packages (from onnxruntime->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (25.9.23)
Requirement already satisfied: iniconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.6.0)
Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (3.5.0)

Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.13.0)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.17.3)
Requirement already satisfied: json5>=0.9.22 in /opt/conda/lib/python3.12/site-packages (from sagemaker_schema_inference_artifacts->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.14.0)
Requirement already satisfied: python-rapidjson>=0.9.1 in /opt/conda/lib/python3.12/site-packages (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.23)
Requirement already satisfied: geventhttpclient<=2.0.2,>=1.4.4 in /opt/conda/lib/python3.12/site-packages (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.0.2)
Requirement already satisfied: gevent>=0.13 in /opt/conda/lib/python3.12/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (26.4.0)
Requirement already satisfied: brotli in /opt/conda/lib/python3.12/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.1.0)

Requirement already satisfied: zope.event in /opt/conda/lib/python3.12/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.2)
Requirement already satisfied: zope.interface in /opt/conda/lib/python3.12/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (8.4)

Requirement already satisfied: sagemaker in /opt/conda/lib/python3.12/site-packages (3.11.0)

Requirement already satisfied: sagemaker-core<3.0.0,>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (2.11.0)
Requirement already satisfied: sagemaker-train<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: sagemaker-serve<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: sagemaker-mlops<2.0.0,>=1.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker) (1.11.0)
Requirement already satisfied: boto3<2.0.0,>=1.42.2 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.42.91)
Requirement already satisfied: pydantic<3.0.0,>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.13.4)
Requirement already satisfied: PyYAML<7.0,>=6.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.0.3)
Requirement already satisfied: jsonschema<5.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.23.0)
Requirement already satisfied: platformdirs<5.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.9.6)
Requirement already satisfied: rich<15.0.0,>=13.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (14.3.4)
Requirement already satisfied: mock<5.0,>4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.3)
Requirement already satisfied: importlib-metadata<7.0,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.10.0)
Requirement already satisfied: typing_extensions>=4.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.15.0)

Requirement already satisfied: pytz>=2021.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2024.2)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.33.1)
Requirement already satisfied: attrs>=20.3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (23.2.0)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (25.0)
Requirement already satisfied: protobuf<7.0.0,>=3.12 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (6.33.6)
Requirement already satisfied: pandas>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.3.3)
Requirement already satisfied: numpy>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.26.4)
Requirement already satisfied: smdebug_rulesconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.0.1)
Requirement already satisfied: schema>=0.7.5 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.7.7)
Requirement already satisfied: omegaconf>=2.1.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.3.0)
Requirement already satisfied: scipy>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.16.3)
Requirement already satisfied: cloudpickle>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.2.1)
Requirement already satisfied: paramiko>=2.11.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.0)
Requirement already satisfied: tblib>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.0.0)
Requirement already satisfied: cryptography>=46.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-core<3.0.0,>=2.11.0->sagemaker) (46.0.7)
Requirement already satisfied: botocore<1.43.0,>=1.42.91 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.42.91)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.1.0)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in /opt/conda/lib/python3.12/site-packages (from boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.16.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.91->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.9.0.post0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.43.0,>=1.42.91->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.26.20)
Requirement already satisfied: zipp>=0.5 in /opt/conda/lib/python3.12/site-packages (from importlib-metadata<7.0,>=1.4.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.23.1)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from jsonschema<5.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.27.1)
Requirement already satisfied: annotated-types>=0.6.0 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /opt/conda/lib/python3.12/site-packages (from pydantic<3.0.0,>=2.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.4.2)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.43.0,>=1.42.91->boto3<2.0.0,>=1.42.2->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.4.7)

Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.13)
Requirement already satisfied: certifi>=2023.5.7 in /opt/conda/lib/python3.12/site-packages (from requests<3.0.0,>=2.20.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2026.4.22)
Requirement already satisfied: markdown-it-py>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /opt/conda/lib/python3.12/site-packages (from rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.20.0)
Requirement already satisfied: pyiceberg>=0.8.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.11.1)
Requirement already satisfied: pyarrow>=14.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (21.0.0)
Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (from sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (2026.3.0)
Requirement already satisfied: deepdiff in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (9.0.0)
Requirement already satisfied: mlflow in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.11.1)
Requirement already satisfied: sagemaker_schema_inference_artifacts in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.0.5)
Requirement already satisfied: pytest in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (9.0.3)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.67.3)
Requirement already satisfied: psutil in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.9.8)
Requirement already satisfied: tritonclient[http] in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.41.1)
Requirement already satisfied: onnx in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.20.0)
Requirement already satisfied: onnxruntime in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.24.2)

Requirement already satisfied: torch>=2.0.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.8.0)
Requirement already satisfied: graphene<4,>=3 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.4.3)
Requirement already satisfied: jinja2<4.0,>=3.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.1.6)
Requirement already satisfied: sagemaker-mlflow<1.0.0,>=0.0.1 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (0.3.0)
Requirement already satisfied: nest_asyncio>=1.5.0 in /opt/conda/lib/python3.12/site-packages (from sagemaker-train<2.0.0,>=1.11.0->sagemaker) (1.6.0)
Requirement already satisfied: graphql-core<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in /opt/conda/lib/python3.12/site-packages (from graphene<4,>=3->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.2.0)
Requirement already satisfied: MarkupSafe>=2.0 in /opt/conda/lib/python3.12/site-packages (from jinja2<4.0,>=3.0->sagemaker-train<2.0.0,>=1.11.0->sagemaker) (3.0.3)
Requirement already satisfied: Flask-CORS<7 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.0.2)
Requirement already satisfied: Flask<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.3)
Requirement already satisfied: aiohttp<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.13.5)
Requirement already satisfied: alembic!=1.10.0,<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.18.4)
Requirement already satisfied: cachetools<8,>=5.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.2.6)
Requirement already satisfied: click<9,>=7.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (8.2.1)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.105.0)
Requirement already satisfied: docker<8,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (7.1.0)
Requirement already satisfied: fastapi<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.136.1)
Requirement already satisfied: gitpython<4,>=3.1.9 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.48)
Requirement already satisfied: gunicorn<26 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (23.0.0)
Requirement already satisfied: huey<3,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.6.0)
Requirement already satisfied: matplotlib<4 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.10.9)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.0)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.41.0)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.2.2)
Requirement already satisfied: scikit-learn<2 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.7.2)
Requirement already satisfied: skops<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.0.49)
Requirement already satisfied: sqlparse<1,>=0.4.0 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.5.0)
Requirement already satisfied: uvicorn<1 in /opt/conda/lib/python3.12/site-packages (from mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.22.0)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.6.1)
Requirement already satisfied: aiosignal>=1.4.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.7.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.23.0)
Requirement already satisfied: Mako in /opt/conda/lib/python3.12/site-packages (from alembic!=1.10.0,<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.3.12)

Requirement already satisfied: cffi>=1.14 in /opt/conda/lib/python3.12/site-packages (from cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.0.0)
Requirement already satisfied: google-auth~=2.0 in /opt/conda/lib/python3.12/site-packages (from databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.49.2)
Requirement already satisfied: starlette>=0.46.0 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in /opt/conda/lib/python3.12/site-packages (from fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.0.4)
Requirement already satisfied: blinker>=1.9.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.9.0)
Requirement already satisfied: itsdangerous>=2.2.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.2.0)
Requirement already satisfied: werkzeug>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from Flask<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.1.8)
Requirement already satisfied: gitdb<5,>=4.0.1 in /opt/conda/lib/python3.12/site-packages (from gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in /opt/conda/lib/python3.12/site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.0.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /opt/conda/lib/python3.12/site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.4.2)
Requirement already satisfied: contourpy>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.62.1)

Requirement already satisfied: kiwisolver>=1.3.1 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.5.0)
Requirement already satisfied: pillow>=8 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (11.3.0)
Requirement already satisfied: pyparsing>=3 in /opt/conda/lib/python3.12/site-packages (from matplotlib<4->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.3.2)
Requirement already satisfied: opentelemetry-semantic-conventions==0.62b0 in /opt/conda/lib/python3.12/site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.62b0)
Requirement already satisfied: tzdata>=2022.7 in /opt/conda/lib/python3.12/site-packages (from pandas>=1.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2026.2)
Requirement already satisfied: joblib>=1.2.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/conda/lib/python3.12/site-packages (from scikit-learn<2->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.6.0)

Requirement already satisfied: prettytable>=3.9 in /opt/conda/lib/python3.12/site-packages (from skops<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.17.0)
Requirement already satisfied: greenlet>=1 in /opt/conda/lib/python3.12/site-packages (from sqlalchemy<3,>=1.4.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.5.0)
Requirement already satisfied: h11>=0.8 in /opt/conda/lib/python3.12/site-packages (from uvicorn<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.16.0)

Requirement already satisfied: pycparser in /opt/conda/lib/python3.12/site-packages (from cffi>=1.14->cryptography>=46.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (2.22)
Requirement already satisfied: mdurl~=0.1 in /opt/conda/lib/python3.12/site-packages (from markdown-it-py>=2.2.0->rich<15.0.0,>=13.0.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (0.1.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /opt/conda/lib/python3.12/site-packages (from omegaconf>=2.1.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (4.9.3)

Requirement already satisfied: bcrypt>=3.2 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (5.0.0)
Requirement already satisfied: invoke>=2.0 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (3.0.3)
Requirement already satisfied: pynacl>=1.5 in /opt/conda/lib/python3.12/site-packages (from paramiko>=2.11.0->sagemaker-core<3.0.0,>=2.11.0->sagemaker) (1.6.2)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.12/site-packages (from prettytable>=3.9->skops<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.6.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /opt/conda/lib/python3.12/site-packages (from pyasn1-modules>=0.2.1->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.6.3)
Requirement already satisfied: mmh3<6.0.0,>=4.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (5.2.1)
Requirement already satisfied: strictyaml<2.0.0,>=1.7.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.7.3)
Requirement already satisfied: fsspec>=2023.1.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (2026.3.0)
Requirement already satisfied: tenacity<10.0.0,>=8.2.3 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (9.1.4)
Requirement already satisfied: pyroaring<2.0.0,>=1.0.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.0.4)
Requirement already satisfied: zstandard<1.0.0,>=0.13.0 in /opt/conda/lib/python3.12/site-packages (from pyiceberg>=0.8.0->pyiceberg[glue]>=0.8.0->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.25.0)

Requirement already satisfied: anyio<5,>=3.6.2 in /opt/conda/lib/python3.12/site-packages (from starlette>=0.46.0->fastapi<1->mlflow->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (4.13.0)
Requirement already satisfied: filelock in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.29.0)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (81.0.0)
Requirement already satisfied: sympy>=1.13.3 in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.14.0)
Requirement already satisfied: networkx in /opt/conda/lib/python3.12/site-packages (from torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (3.6.1)
Requirement already satisfied: mpmath<1.5,>=1.1.0 in /opt/conda/lib/python3.12/site-packages (from sympy>=1.13.3->torch>=2.0.0->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.4.1)
Requirement already satisfied: orderly-set<6,>=5.5.0 in /opt/conda/lib/python3.12/site-packages (from deepdiff->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (5.5.0)

Requirement already satisfied: ml_dtypes>=0.5.0 in /opt/conda/lib/python3.12/site-packages (from onnx->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.5.4)
Requirement already satisfied: flatbuffers in /opt/conda/lib/python3.12/site-packages (from onnxruntime->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (25.9.23)
Requirement already satisfied: iniconfig>=1.0.1 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /opt/conda/lib/python3.12/site-packages (from pytest->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.6.0)

Requirement already satisfied: aiobotocore<4.0.0,>=2.19.0 in /opt/conda/lib/python3.12/site-packages (from s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (3.5.0)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (0.13.0)
Requirement already satisfied: wrapt<3.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<4.0.0,>=2.19.0->s3fs->sagemaker-mlops<2.0.0,>=1.11.0->sagemaker) (1.17.3)
Requirement already satisfied: json5>=0.9.22 in /opt/conda/lib/python3.12/site-packages (from sagemaker_schema_inference_artifacts->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (0.14.0)

Requirement already satisfied: python-rapidjson>=0.9.1 in /opt/conda/lib/python3.12/site-packages (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.23)
Requirement already satisfied: geventhttpclient<=2.0.2,>=1.4.4 in /opt/conda/lib/python3.12/site-packages (from tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (2.0.2)
Requirement already satisfied: gevent>=0.13 in /opt/conda/lib/python3.12/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (26.4.0)
Requirement already satisfied: brotli in /opt/conda/lib/python3.12/site-packages (from geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (1.1.0)
Requirement already satisfied: zope.event in /opt/conda/lib/python3.12/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (6.2)
Requirement already satisfied: zope.interface in /opt/conda/lib/python3.12/site-packages (from gevent>=0.13->geventhttpclient<=2.0.2,>=1.4.4->tritonclient[http]->sagemaker-serve<2.0.0,>=1.11.0->sagemaker) (8.4)

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__']

In [2]:
# Step 1: Setup
import sagemaker, boto3, time
#from sagemaker import get_execution_role
import pandas as pd
from time import gmtime, strftime
from sklearn.model_selection import train_test_split 

try:
    from sagemaker import get_execution_role
    role = get_execution_role()
except:
    import boto3
    role = boto3.client("sts").get_caller_identity()["Arn"]

region = boto3.Session().region_name

# S3 bucket for storing data
bucket = 'sagemaker-eu-central-1-112242697189'

# Load the dataset
file_path = 'Employee.csv'
employee_df = pd.read_csv(file_path)
employee_df.head()

,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain,LeaveOrNot
0,Bachelors,2017,Bangalore,3,34,Male,No,0,0
1,Bachelors,2013,Pune,1,28,Female,No,3,1
2,Bachelors,2014,New Delhi,3,38,Female,No,2,0
3,Masters,2016,Bangalore,3,27,Male,No,5,1
4,Masters,2017,Pune,3,24,Male,Yes,2,1

In [3]:
# Step 2: Data Preparation
# Convert categorical columns to numeric
employee_df['Education'] = employee_df['Education'].astype('category').cat.codes
employee_df['City'] = employee_df['City'].astype('category').cat.codes
employee_df['Gender'] = employee_df['Gender'].astype('category').cat.codes
employee_df['EverBenched'] = employee_df['EverBenched'].map({'Yes': 1, 'No': 0})

# Drop rows with NaN values in the target column
employee_df.dropna(subset=['LeaveOrNot'])

# Convert target column to numeric if needed
employee_df['LeaveOrNot'] = employee_df['LeaveOrNot'].astype(int)

# Ensure no missing values in feature columns
employee_df = employee_df.dropna()

# Verify all columns are numeric
print(employee_df.dtypes)

# Define features and target
feature_columns = ['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age','Gender', 'EverBenched', 'ExperienceInCurrentDomain']
target_column = 'LeaveOrNot'

employee_df = employee_df[[target_column] + feature_columns]

# Display the transformed dataset
employee_df.head()

Education                     int8
JoiningYear                  int64
City                          int8
PaymentTier                  int64
Age                          int64
Gender                        int8
EverBenched                  int64
ExperienceInCurrentDomain    int64
LeaveOrNot                   int64
dtype: object

,LeaveOrNot,Education,JoiningYear,City,PaymentTier,Age,Gender,EverBenched,ExperienceInCurrentDomain
0,0,0,2017,0,3,34,1,0,0
1,1,0,2013,2,1,28,0,0,3
2,0,0,2014,1,3,38,0,0,2
3,1,1,2016,0,3,27,1,0,5
4,1,1,2017,2,3,24,1,1,2

In [4]:
# Use the existing SageMaker execution role
role = 'arn:aws:iam::112242697189:role/service-role/AmazonSageMaker-ExecutionRole-20260506T092538'

# Create boto3 clients
sagemaker_client = boto3.client('sagemaker')
featurestore_client = boto3.client('sagemaker-featurestore-runtime')

# Create feature group name
feature_group_name = 'employee-feature-group-' + strftime('%Y%m%d%H%M%S', gmtime())

# Define schema
record_identifier_name = 'EmployeeID'
event_time_feature_name = 'EventTime'

# Prepare data
employee_df[event_time_feature_name] = pd.to_datetime('now').strftime('%Y-%m-%dT%H:%M:%S.%fZ')
employee_df[record_identifier_name] = employee_df.index

# Create feature definitions from DataFrame
feature_definitions = []
for col in employee_df.columns:
    dtype = str(employee_df[col].dtype)
    if 'int' in dtype:
        feature_type = 'Integral'
    elif 'float' in dtype:
        feature_type = 'Fractional'
    else:
        feature_type = 'String'
    
    feature_definitions.append({'FeatureName': col,'FeatureType': feature_type})

# Create feature group
sagemaker_client.create_feature_group(
                                        FeatureGroupName=feature_group_name,
                                        RecordIdentifierFeatureName=record_identifier_name,
                                        EventTimeFeatureName=event_time_feature_name,
                                        FeatureDefinitions=feature_definitions,
                                        OnlineStoreConfig={'EnableOnlineStore': True},
                                        OfflineStoreConfig={'S3StorageConfig': {'S3Uri': 's3://sagemaker-eu-central-1-112242697189/features'}},
                                        RoleArn=role
                                        )

{'FeatureGroupArn': 'arn:aws:sagemaker:eu-central-1:112242697189:feature-group/employee-feature-group-20260514090649',
 'ResponseMetadata': {'RequestId': 'ecf5f5c9-9f4e-48e3-b0a0-afd8c67148ab',
  'HTTPStatusCode': 200,
  'HTTPHeaders': {'x-amzn-requestid': 'ecf5f5c9-9f4e-48e3-b0a0-afd8c67148ab',
   'strict-transport-security': 'max-age=47304000; includeSubDomains',
   'x-frame-options': 'DENY',
   'content-security-policy': "frame-ancestors 'none'",
   'cache-control': 'no-cache, no-store, must-revalidate',
   'x-content-type-options': 'nosniff',
   'content-type': 'application/x-amz-json-1.1',
   'content-length': '117',
   'date': 'Thu, 14 May 2026 09:06:50 GMT'},
  'RetryAttempts': 0}}

In [5]:
# Check the status of the Feature Group
response = sagemaker_client.describe_feature_group(FeatureGroupName=feature_group_name)
status = response.get("FeatureGroupStatus")
print(f"Feature Group Status: {status}")

# Wait for feature group to be created
while status == "Creating":
    print("Waiting for feature group to be created...")
    time.sleep(30)
    response = sagemaker_client.describe_feature_group(FeatureGroupName=feature_group_name)
    status = response.get("FeatureGroupStatus")

if status == "Created":
    print("Feature Group is Created and ready for use. Proceeding with ingestion...")
    
    # Convert DataFrame to records for ingestion
    records = []
    for _, row in employee_df.iterrows():
        record = []
        for col in employee_df.columns:
            value = str(row[col])
            record.append({
                'FeatureName': col,
                'ValueAsString': value
            })
        records.append({
            'Record': record
        })
    
    # Ingest data into the Feature Store
    featurestore_client.put_record(FeatureGroupName=feature_group_name,Record=records[0]['Record'])
    
    # For multiple records, use batch ingestion
    for record in records:
        featurestore_client.put_record(FeatureGroupName=feature_group_name,Record=record['Record'])
    print('Data ingested into Feature Store.')

Feature Group Status: Creating
Waiting for feature group to be created...

Feature Group is Created and ready for use. Proceeding with ingestion...

Data ingested into Feature Store.

In [6]:
# Define the feature group name and features you want to retrieve
feature_names = ['Education', 'JoiningYear', 'City', 'PaymentTier', 'Age', 'Gender', 'EverBenched', 'ExperienceInCurrentDomain', 'LeaveOrNot']

# Retrieve records and convert to DataFrame
records = []
for record_id in employee_df.index.astype(str):
    try:
        response = featurestore_client.get_record(FeatureGroupName=feature_group_name,RecordIdentifierValueAsString=str(record_id),FeatureNames=feature_names)
        # Check if 'Record' is in the response and add to records list
        if 'Record' in response:
            record = {feature['FeatureName']: feature['ValueAsString'] for feature in response['Record']}
            records.append(record)
        else:
            print(f"Record with ID {record_id} not found.")
    except Exception as e:
        print(f"Error retrieving record {record_id}: {e}")

# Convert the list of records to a DataFrame
retrieved_df = pd.DataFrame(records)

# Check if we have any retrieved records
if not retrieved_df.empty:
    # Split the data into training and test sets
    train_df, test_df = train_test_split(retrieved_df, test_size=0.2, random_state=42)
    print("Training and test data split after retrieval from Feature Store.")
else:
    print("No records retrieved. Please check the feature group and identifiers.")

Training and test data split after retrieval from Feature Store.

## Train the Model Using Local Data with S3 Mode (Default)

In [7]:
# Initialize S3 client
s3 = boto3.client('s3')

# Define your S3 bucket and prefix
bucket = 'sagemaker-eu-central-1-112242697189'
prefix = 'input-data'

# Save the data locally first
train_file = 'train.csv'
validation_file = 'validation.csv'
train_df.to_csv(train_file, index=False)
test_df.to_csv(validation_file, index=False)

# Upload the data to S3
s3.upload_file(train_file, bucket, f'{prefix}/train/{train_file}')
s3.upload_file(validation_file, bucket, f'{prefix}/validation/{validation_file}')

print(f"Training data uploaded to s3://{bucket}/{prefix}/train/{train_file}")
print(f"Validation data uploaded to s3://{bucket}/{prefix}/validation/{validation_file}")

Training data uploaded to s3://sagemaker-eu-central-1-112242697189/input-data/train/train.csv
Validation data uploaded to s3://sagemaker-eu-central-1-112242697189/input-data/validation/validation.csv

In [8]:
# Initialize hyperparameters
hyperparameters = {
                    "max_depth": "12",
                    "eta": "0.2",
                    "gamma": "0",
                    "min_child_weight": "6",
                    "learning_rate": "0.01",
                    "subsample": "0.7",
                    "objective": "reg:squarederror",
                    "num_round": "100",
                    "early_stopping_rounds": "25",
                    "colsample_bytree": "0.8",
                    "n_estimators": "900",
                    }

# Set paths
bucket = 'sagemaker-eu-central-1-112242697189'
prefix = 'demo-built-in-algorithm'
output_path = f's3://{bucket}/{prefix}/output'
role = 'arn:aws:iam::112242697189:role/service-role/AmazonSageMaker-ExecutionRole-20260506T092538'

# Get XGBoost container URI
region = boto3.Session().region_name
xgboost_container = f"246618743249.dkr.ecr.{region}.amazonaws.com/sagemaker-xgboost:1.7-1"

# Create SageMaker client
sagemaker_client = boto3.client('sagemaker')

# Create training job
training_job_name = f'xgboost-employee-attrition-{int(time.time())}'

response = sagemaker_client.create_training_job(
    TrainingJobName=training_job_name,
    RoleArn=role,
    AlgorithmSpecification={'TrainingImage': xgboost_container,'TrainingInputMode': 'File'},
    InputDataConfig=[
        {
            'ChannelName': 'train',
            'DataSource': {
                'S3DataSource': {
                    'S3DataType': 'S3Prefix',
                    'S3Uri': f's3://{bucket}/input-data/train/',
                    'S3DataDistributionType': 'FullyReplicated'}},'ContentType': 'csv'},
        {
            'ChannelName': 'validation',
            'DataSource': {
                'S3DataSource': {
                    'S3DataType': 'S3Prefix',
                    'S3Uri': f's3://{bucket}/input-data/validation/',
                    'S3DataDistributionType': 'FullyReplicated'}},'ContentType': 'csv'}],
    OutputDataConfig={'S3OutputPath': output_path},
    ResourceConfig={'InstanceType': 'ml.m5.xlarge','InstanceCount': 1,'VolumeSizeInGB': 5},
    StoppingCondition={'MaxRuntimeInSeconds': 3600},
    HyperParameters=hyperparameters
)

print(f"Training job started: {training_job_name}")

Training job started: xgboost-employee-attrition-1778749727